root: true
env:
  browser: true
  node: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  project: './tsconfig.json'
extends: [
  "eslint:recommended",
  "plugin:@typescript-eslint/eslint-recommended",
  "plugin:@typescript-eslint/recommended",
  "plugin:prettier/recommended",
  "plugin:prettier/recommended"
]
plugins: [
  'prettier',
  '@typescript-eslint'
]
# rules: 
